version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: medusa_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: medusa-store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - medusa_network

  redis:
    image: redis:7-alpine
    container_name: medusa_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - medusa_network

  backend:
    build: ./backend
    container_name: medusa_backend
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    env_file:
      - ./backend/.env
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/server
      - /server/node_modules
    networks:
      - medusa_network

  admin-dashboard:
    build: ./admin-dashboard
    container_name: admin_dashboard
    restart: unless-stopped
    depends_on:
      - backend
    env_file:
      - ./admin-dashboard/.env
    environment:
      - VITE_MEDUSA_BACKEND_URL=http://localhost:9000
      - VITE_MEDUSA_PROJECT=/backend
    ports:
      - "5173:5173"
    volumes:
      - ./admin-dashboard:/app
      - ./backend:/backend
      - /app/node_modules
    command: >
      sh -c "npm run dev -- --host 0.0.0.0 --port 5173"
    networks:
      - medusa_network

volumes:
  postgres_data:

networks:
  medusa_network:
    driver: bridge


# docker compose exec backend npx medusa user -e admin@example.com -p supersecret
# 上記でスーパーアドミンを作成